INSERT INTO PolytechnicModules (moduleName, moduleCode)
VALUES
('Computing Mathematics', 'IT1325'),
('Data Structures & Programming Techniques', 'IT1506'),
('Web Applications Development', 'IT1507'),
('Business Communication 1', 'BM0030'),
('Principles of Accounting', 'BM0031'),
('Essentials of Marketing', 'BM0032'),
('Networking Essential', 'IT1608'),
('Law & Ethics of IT', 'IT1324'),
('Business Statistics', 'IT1333'),
('Principles of Economics', 'BM0035'),
('Object-Oriented Programming & Project', 'ITP182'),
('Database Management Systems', 'IT2201'),
('Business Communication 2', 'BM0501'),
('Business Environment', 'BM0518'),
('Financial Management', 'BM0519'),
('Management Principle', 'BM0036'),
('International Business', 'BM0522'),
('Software Engineering Practices', 'IT2535'),
('Applications of Web Services', 'IT2605'),
('e-Business & Project', 'ITP281'),
('Enterprise Applications Development & Project', 'ITP282'),
('InfoSecurity Technology', 'IT2118'),
('Business Informatics Project', 'ITP381'),
('Internship Programme', 'IT3763'),
('Final Year Project', 'IT3331'),
('Entrepreneurship', 'BM0515'),
('Market Research', 'BM0505'),
('Service Science and Innovation', 'IT3651'),
('Services Marketing Management', 'BM0523'),
('Mobile Services and Applications', 'IT2656'),
('Business Intelligence and Analytics', 'IT3556'),
('Cloud Computing for Business Applications', 'IT3557'),
('Programming Essentials', 'IT1111'),
('Psychology & Sociology', 'IT1323'),
('Object-Oriented Programming', 'IT1331'),
('Consumer Behaviour', 'IT1334'),
('Communication Skills 1', 'IT1110'),
('Principles of Web Usability Design & Project', 'ITP131'),
('Social Media Applications & Project', 'ITP132'),
('Quantitative Methods', 'IT2322'),
('Network Technology', 'IT1533'),
('Communication Skills 2', 'IT1210'),
('Industry Analysis', 'IT2331'),
('Advanced Database Systems', 'IT2333'),
('Predictive Modelling', 'IT2335'),
('Mobile Application Development & Project', 'ITP231'),
('Business Analytics & Visualisation Project', 'ITP232'),
('Data Privacy & Security', 'IT3322'),
('Enterprise Business Analytics Project', 'ITP331'),
('Analytics for Financial Services', 'IT3351'),
('Analytics for Retail & Hospitality', 'IT3353'),
('Big Data Analytics', 'IT3359'),
('Social Media Analytics', 'IT3355'),
('Digital Marketing & Analytics', 'IT3135'),
('Geospatial Analytics', 'IT3358'),
('Cyber Security Technology, Law & Ethics', 'IT1528'),
('Cryptography & Applications', 'IT1534'),
('Computing Mathematics 1', 'IT1101'),
('Computing Mathematics 2', 'IT1201'),
('Web Applications Development & Project', 'ITP111'),
('Risk & Incident Management', 'IT2522'),
('Servers & Services Security Management', 'IT2533'),
('InfoSecurity Standards, Policies and Audit', 'IT2534'),
('Cyber Forensic Technologies', 'IT2537'),
('Operating Systems', 'IT1205'),
('Data Structures & Algorithms', 'IT1204'),
('Network Security & Project', 'ITP291'),
('Applications Security & Project', 'ITP311'),
('InfoSecurity Governance', 'IT3523'),
('Operations Security & Case Study', 'ITP391'),
('Digital Rights Management', 'IT3541'),
('IT Project Management', 'IT3542'),
('Cloud Computing Security', 'IT3546'),
('Cyber Security Attack & Defense', 'IT3526'),
('Cyber Security Operations & Intelligence', 'IT3549'),
('Mobile Security', 'IT3548'),
('Cyber Forensic Process', 'IT3525'),
('Disaster Recovery & Business Continuity Management', 'IT3545'),
('Advanced Cyber Forensic Techniques', 'IT3543'),
('Malware Analysis', 'IT3547'),
('Trends in Fintech & Services', 'IT1622'),
('Economics', 'IT1634'),
('Consumer Banking', 'IT1636'),
('Capital Markets and Financial Instruments', 'IT1633'),
('Risk Management', 'IT2634'),
('Cyber Security for Financial Services', 'IT2633'),
('Law, Governance & Ethics', 'IT2626'),
('Business Analytics & Project', 'ITP262'),
('Emerging Fintech', 'IT3621'),
('Fintech Innovation Project', 'ITP361'),
('Investment and Financial Derivatives', 'IT2635'),
('International Finance and Treasury', 'IT3642'),
('Personal Financial Planning and Insurance', 'IT3643'),
('Enterprise Solutions', 'IT3622'),
('Business Process Management', 'IT3623')
('Principles of Computing', 'IT1753'),
('Database Systems', 'IT1768'),
('Infocomm Security Fundamentals', 'IT1773'),
('IT Fundamentals & Project', 'ITP171'),
('Networking Fundamentals & Project', 'ITP172'),
('Software Engineering', 'IT2116'),
('Network and Communications', 'IT2762'),
('IT Services & Management', 'IT2768'),
('Operations Security', 'IT2775'),
('Rich Internet Application Development', 'IT2771'),
('Network Security', 'IT2774'),
('Sensor Technologies & Project', 'ITP272'),
('Smart Object Technologies', 'IT3779'),
('Systems & Network Security Project', 'ITP374'),
('Computer & Network Forensics', 'IT3784'),
('Cyber Security Operations', 'IT3549'),
('Cyber Security Attack & Defense', 'IT3526'),
('Enterprise Networking & Project', 'ITP372'),
('Enterprise Systems Administration', 'IT3787'),
('Virtualisation & Data Centre Management', 'IT3790'),
('Open Systems Administration', 'IT3797'),
('IT Services Operations Management', 'IT3799'),
('Enterprise Software Development & Project', 'ITP371'),
('Mobile Applications Development', 'IT3783'),
('Database Administration', 'IT3795'),
('Open Source Technologies Development', 'IT3800'),
('Data Analytics & Visualisation', 'IT3786'),
('Global Supply Chain Management & Project', 'ITP373'),
('Logistics & Distribution', 'IT3792'),
('Advanced Planning & Optimisation', 'IT3793'),
('Operations Management', 'IT3794'),
('Data Communications & Networking', 'IT1213'),
('IP Technology & Networking', 'IT2106'),
('Digital Media Interaction Design', 'IT1214'),
('Mobile Usability Design', 'IT2107'),
('Object-Oriented Analysis, Design & Project', 'ITP211'),
('C# Application Development', 'IT2127'),
('C++ Application Development', 'IT2128'),
('Java Enterprise Development & Project', 'ITP212'),
('Emerging Trends & Technologies', 'IT3180'),
('InfoSecurity Management', 'IT3111'),
('System & Network Security', 'IT3112'),
('Digital Forensics', 'IT3118'),
('Concepts of Geospatial Information System', 'IT3160'),
('Geospatial Visualisation', 'IT3161'),
('Cloud Computing', 'IT3178'),
('Smart Device Development & Project', 'ITP312'),
('Psychology & Sociology for Online Media', 'IT3125'),
('Enterprise Social Media', 'IT3127'),
('Social Media Marketing & Analytics', 'IT3128'),
('Social Media Technologies & Project', 'ITP313');