INSERT INTO Skills (skill) VALUES ('Python');
INSERT INTO Skills (skill) VALUES ('C++');
INSERT INTO Skills (skill) VALUES ('C');
INSERT INTO Skills (skill) VALUES ('Assembly');
INSERT INTO Skills (skill) VALUES ('C#');
INSERT INTO Skills (skill) VALUES ('F#');
INSERT INTO Skills (skill) VALUES ('Elixir');
INSERT INTO Skills (skill) VALUES ('Puppet');
INSERT INTO Skills (skill) VALUES ('Jenkins');
INSERT INTO Skills (skill) VALUES ('NodeJS');
INSERT INTO Skills (skill) VALUES ('DevSecOps');
INSERT INTO Skills (skill) VALUES ('Swift');
INSERT INTO Skills (skill) VALUES ('HTML');
INSERT INTO Skills (skill) VALUES ('CSS');
INSERT INTO Skills (skill) VALUES ('React');
INSERT INTO Skills (skill) VALUES ('React Native');
INSERT INTO Skills (skill) VALUES ('JavaScript');
INSERT INTO Skills (skill) VALUES ('Java');
INSERT INTO Skills (skill) VALUES ('Ruby');
INSERT INTO Skills (skill) VALUES ('PowerShell');
INSERT INTO Skills (skill) VALUES ('Access');
INSERT INTO Skills (skill) VALUES ('SQL');
INSERT INTO Skills (skill) VALUES ('XQuery');
INSERT INTO Skills (skill) VALUES ('XML');
INSERT INTO Skills (skill) VALUES ('Statistics');
INSERT INTO Skills (skill) VALUES ('Networking');
INSERT INTO Skills (skill) VALUES ('AWS');
INSERT INTO Skills (skill) VALUES ('Google Cloud');
INSERT INTO Skills (skill) VALUES ('Microsoft Azure');
INSERT INTO Skills (skill) VALUES ('Oracle');
INSERT INTO Skills (skill) VALUES ('MongoDb');
INSERT INTO Skills (skill) VALUES ('MySQL');
INSERT INTO Skills (skill) VALUES ('Kernels');
INSERT INTO Skills (skill) VALUES ('Internet of Things');
INSERT INTO Skills (skill) VALUES ('Networking');
INSERT INTO Skills (skill) VALUES ('Cloud Computing');
INSERT INTO Skills (skill) VALUES ('Data Mining');
INSERT INTO Skills (skill) VALUES ('Data Crawling');
INSERT INTO Skills (skill) VALUES ('DevOps');
INSERT INTO Skills (skill) VALUES ('Data Science');
INSERT INTO Skills (skill) VALUES ('Web Development');
INSERT INTO Skills (skill) VALUES ('User Interface Design');
INSERT INTO Skills (skill) VALUES ('UI/UX');
INSERT INTO Skills (skill) VALUES ('System Architecture');
INSERT INTO Skills (skill) VALUES ('Apache');
INSERT INTO Skills (skill) VALUES ('C-- (C minus minus)');
INSERT INTO Skills (skill) VALUES ('C++ (C plus plus)');
INSERT INTO Skills (skill) VALUES ('C# (C sharp)');
INSERT INTO Skills (skill) VALUES ('C');
INSERT INTO Skills (skill) VALUES ('C Shell (csh)');
INSERT INTO Skills (skill) VALUES ('Carbon');
INSERT INTO Skills (skill) VALUES ('COBOL');
INSERT INTO Skills (skill) VALUES ('Datalog');
INSERT INTO Skills (skill) VALUES ('F');
INSERT INTO Skills (skill) VALUES ('F# (F sharp)');
INSERT INTO Skills (skill) VALUES ('F*');
INSERT INTO Skills (skill) VALUES ('Factor');
INSERT INTO Skills (skill) VALUES ('FlagShip');
INSERT INTO Skills (skill) VALUES ('F-Script');
INSERT INTO Skills (skill) VALUES ('Hopscotch');
INSERT INTO Skills (skill) VALUES ('Machine code');
INSERT INTO Skills (skill) VALUES ('Net.Data');
INSERT INTO Skills (skill) VALUES ('NPL');
INSERT INTO Skills (skill) VALUES ('Open Programming Language (OPL)');
INSERT INTO Skills (skill) VALUES ('OpenEdge Advanced Business Language (ABL)');
INSERT INTO Skills (skill) VALUES ('PHP');
INSERT INTO Skills (skill) VALUES ('Pico');
INSERT INTO Skills (skill) VALUES ('Pipelines');
INSERT INTO Skills (skill) VALUES ('Q (programming language from Kx Systems)');
INSERT INTO Skills (skill) VALUES ('Q# (Microsoft programming language)');
INSERT INTO Skills (skill) VALUES ('Swift');
INSERT INTO Skills (skill) VALUES ('SQL');
INSERT INTO Skills (skill) VALUES ('MYSQL');
INSERT INTO Skills (skill) VALUES ('TypeScript');
INSERT INTO Skills (skill) VALUES ('Tynker');
INSERT INTO Skills (skill) VALUES ('UNITY');
INSERT INTO Skills (skill) VALUES ('Xtend');