INSERT INTO Skills (skill) VALUES ('Data structure and algorithm');
INSERT INTO Skills (skill) VALUES ('Python');
INSERT INTO Skills (skill) VALUES ('C++');
INSERT INTO Skills (skill) VALUES ('C');
INSERT INTO Skills (skill) VALUES ('Assembly');
INSERT INTO Skills (skill) VALUES ('C#');
INSERT INTO Skills (skill) VALUES ('F#');
INSERT INTO Skills (skill) VALUES ('Clojure');
INSERT INTO Skills (skill) VALUES ('Elixir');
INSERT INTO Skills (skill) VALUES ('PureScript');
INSERT INTO Skills (skill) VALUES ('Docker');
INSERT INTO Skills (skill) VALUES ('Kubernetes');
INSERT INTO Skills (skill) VALUES ('Ansible');
INSERT INTO Skills (skill) VALUES ('Chef');
INSERT INTO Skills (skill) VALUES ('Puppet');
INSERT INTO Skills (skill) VALUES ('Jenkins');
INSERT INTO Skills (skill) VALUES ('NodeJS');
INSERT INTO Skills (skill) VALUES ('DevSecOps');
INSERT INTO Skills (skill) VALUES ('Swift');
INSERT INTO Skills (skill) VALUES ('Go');
INSERT INTO Skills (skill) VALUES ('Dart');
INSERT INTO Skills (skill) VALUES ('Apache Groovy');
INSERT INTO Skills (skill) VALUES ('Java 17');
INSERT INTO Skills (skill) VALUES ('Crystal');
INSERT INTO Skills (skill) VALUES ('HTML');
INSERT INTO Skills (skill) VALUES ('CSS');
INSERT INTO Skills (skill) VALUES ('React');
INSERT INTO Skills (skill) VALUES ('React Native');
INSERT INTO Skills (skill) VALUES ('JavaScript');
INSERT INTO Skills (skill) VALUES ('CouchDB');
INSERT INTO Skills (skill) VALUES ('Java');
INSERT INTO Skills (skill) VALUES ('Ruby');
INSERT INTO Skills (skill) VALUES ('PowerShell');
INSERT INTO Skills (skill) VALUES ('Access');
INSERT INTO Skills (skill) VALUES ('SQL');
INSERT INTO Skills (skill) VALUES ('XQuery');
INSERT INTO Skills (skill) VALUES ('OQL');
INSERT INTO Skills (skill) VALUES ('LINQ');
INSERT INTO Skills (skill) VALUES ('XML');
INSERT INTO Skills (skill) VALUES ('GraphQL');
INSERT INTO Skills (skill) VALUES ('Statistics');
INSERT INTO Skills (skill) VALUES ('Networking');
INSERT INTO Skills (skill) VALUES ('AWS');
INSERT INTO Skills (skill) VALUES ('Google Cloud');
INSERT INTO Skills (skill) VALUES ('Microsoft Azure');
INSERT INTO Skills (skill) VALUES ('Oracle');
INSERT INTO Skills (skill) VALUES ('MongoDb');
INSERT INTO Skills (skill) VALUES ('MySQL');
INSERT INTO Skills (skill) VALUES ('Parametric and nonparametric algorithms');
INSERT INTO Skills (skill) VALUES ('Kernels');
INSERT INTO Skills (skill) VALUES ('Clustering');
INSERT INTO Skills (skill) VALUES ('Deep learning techniques');
INSERT INTO Skills (skill) VALUES ('Internet of Things');
INSERT INTO Skills (skill) VALUES ('Network Management');
INSERT INTO Skills (skill) VALUES ('Network Infrastructure');
INSERT INTO Skills (skill) VALUES ('Cloud Computing');
INSERT INTO Skills (skill) VALUES ('Cloud Platforms');
INSERT INTO Skills (skill) VALUES ('Cloud Infrastructure');
INSERT INTO Skills (skill) VALUES ('Data Mining');
INSERT INTO Skills (skill) VALUES ('Data Crawling');
INSERT INTO Skills (skill) VALUES ('DevOps');
INSERT INTO Skills (skill) VALUES ('Digital Advertising');
INSERT INTO Skills (skill) VALUES ('Data Science');
INSERT INTO Skills (skill) VALUES ('Web Development');
INSERT INTO Skills (skill) VALUES ('User Interface Design');
INSERT INTO Skills (skill) VALUES ('UI/UX');
INSERT INTO Skills (skill) VALUES ('System Architecture');
INSERT INTO Skills (skill) VALUES ('A.NET (A#/A sharp)');
INSERT INTO Skills (skill) VALUES ('A-0 System');
INSERT INTO Skills (skill) VALUES ('A+ (A plus)');
INSERT INTO Skills (skill) VALUES ('A++');
INSERT INTO Skills (skill) VALUES ('ABAP');
INSERT INTO Skills (skill) VALUES ('ABC');
INSERT INTO Skills (skill) VALUES ('ABC ALGOL');
INSERT INTO Skills (skill) VALUES ('ACC');
INSERT INTO Skills (skill) VALUES ('Accent (Rational Synergy)');
INSERT INTO Skills (skill) VALUES ('Ace DASL (Distributed Application Specification Language)');
INSERT INTO Skills (skill) VALUES ('Action!');
INSERT INTO Skills (skill) VALUES ('ActionScript');
INSERT INTO Skills (skill) VALUES ('Actor');
INSERT INTO Skills (skill) VALUES ('Ada – ISO/IEC 8652');
INSERT INTO Skills (skill) VALUES ('Adenine (Haystack)');
INSERT INTO Skills (skill) VALUES ('AdvPL');
INSERT INTO Skills (skill) VALUES ('Agda');
INSERT INTO Skills (skill) VALUES ('Agilent VEE (Keysight VEE)');
INSERT INTO Skills (skill) VALUES ('Agora');
INSERT INTO Skills (skill) VALUES ('AIMMS');
INSERT INTO Skills (skill) VALUES ('Aldor');
INSERT INTO Skills (skill) VALUES ('Alef');
INSERT INTO Skills (skill) VALUES ('ALF');
INSERT INTO Skills (skill) VALUES ('ALGOL 58');
INSERT INTO Skills (skill) VALUES ('ALGOL 60');
INSERT INTO Skills (skill) VALUES ('ALGOL 68');
INSERT INTO Skills (skill) VALUES ('ALGOL W');
INSERT INTO Skills (skill) VALUES ('Alice (Alice ML)');
INSERT INTO Skills (skill) VALUES ('Alma-0');
INSERT INTO Skills (skill) VALUES ('AmbientTalk');
INSERT INTO Skills (skill) VALUES ('Amiga E');
INSERT INTO Skills (skill) VALUES ('AMOS (AMOS BASIC)');
INSERT INTO Skills (skill) VALUES ('AMPL');
INSERT INTO Skills (skill) VALUES ('Analitik');
INSERT INTO Skills (skill) VALUES ('AngelScript');
INSERT INTO Skills (skill) VALUES ('Apache Pig latin');
INSERT INTO Skills (skill) VALUES ('Apex ([Salesforce.com](http://salesforce.com/), Inc)');
INSERT INTO Skills (skill) VALUES ('APL');
INSERT INTO Skills (skill) VALUES ('App Inventor for Android''s visual block language (MIT App Inventor)');
INSERT INTO Skills (skill) VALUES ('AppleScript');
INSERT INTO Skills (skill) VALUES ('APT');
INSERT INTO Skills (skill) VALUES ('Arc');
INSERT INTO Skills (skill) VALUES ('ARexx');
INSERT INTO Skills (skill) VALUES ('Argus');
INSERT INTO Skills (skill) VALUES ('Assembly language (ASM)');
INSERT INTO Skills (skill) VALUES ('AutoHotkey');
INSERT INTO Skills (skill) VALUES ('AutoIt');
INSERT INTO Skills (skill) VALUES ('AutoLISP / Visual LISP');
INSERT INTO Skills (skill) VALUES ('Averest');
INSERT INTO Skills (skill) VALUES ('AWK');
INSERT INTO Skills (skill) VALUES ('Axum');
INSERT INTO Skills (skill) VALUES ('B');
INSERT INTO Skills (skill) VALUES ('Babbage');
INSERT INTO Skills (skill) VALUES ('Ballerina');
INSERT INTO Skills (skill) VALUES ('Bash');
INSERT INTO Skills (skill) VALUES ('BASIC');
INSERT INTO Skills (skill) VALUES ('Batch file (Windows/MS-DOS)');
INSERT INTO Skills (skill) VALUES ('bc (basic calculator)');
INSERT INTO Skills (skill) VALUES ('BCPL');
INSERT INTO Skills (skill) VALUES ('BeanShell');
INSERT INTO Skills (skill) VALUES ('BETA');
INSERT INTO Skills (skill) VALUES ('BLISS');
INSERT INTO Skills (skill) VALUES ('Blockly');
INSERT INTO Skills (skill) VALUES ('BlooP');
INSERT INTO Skills (skill) VALUES ('Boo');
INSERT INTO Skills (skill) VALUES ('Boomerang');
INSERT INTO Skills (skill) VALUES ('Bosque');
INSERT INTO Skills (skill) VALUES ('C – ISO/IEC 9899');
INSERT INTO Skills (skill) VALUES ('C-- (C minus minus)');
INSERT INTO Skills (skill) VALUES ('C++ (C plus plus) – ISO/IEC 14882');
INSERT INTO Skills (skill) VALUES ('C*');
INSERT INTO Skills (skill) VALUES ('C# (C sharp) – ISO/IEC 23270');
INSERT INTO Skills (skill) VALUES ('C/AL');
INSERT INTO Skills (skill) VALUES ('Caché ObjectScript');
INSERT INTO Skills (skill) VALUES ('C Shell (csh)');
INSERT INTO Skills (skill) VALUES ('Caml');
INSERT INTO Skills (skill) VALUES ('Carbon');
INSERT INTO Skills (skill) VALUES ('Catrobat');
INSERT INTO Skills (skill) VALUES ('Cayenne (Lennart Augustsson)');
INSERT INTO Skills (skill) VALUES ('CDuce');
INSERT INTO Skills (skill) VALUES ('Cecil');
INSERT INTO Skills (skill) VALUES ('CESIL (Computer Education in Schools Instruction Language)');
INSERT INTO Skills (skill) VALUES ('Céu');
INSERT INTO Skills (skill) VALUES ('Ceylon');
INSERT INTO Skills (skill) VALUES ('CFEngine');
INSERT INTO Skills (skill) VALUES ('Cg (High-Level Shader/Shading Language [HLSL])');
INSERT INTO Skills (skill) VALUES ('Ch');
INSERT INTO Skills (skill) VALUES ('Chapel (Cascade High Productivity Language)');
INSERT INTO Skills (skill) VALUES ('Charm');
INSERT INTO Skills (skill) VALUES ('CHILL');
INSERT INTO Skills (skill) VALUES ('CHIP-8');
INSERT INTO Skills (skill) VALUES ('ChucK');
INSERT INTO Skills (skill) VALUES ('Cilk (also Cilk++ and Cilk plus)');
INSERT INTO Skills (skill) VALUES ('Claire');
INSERT INTO Skills (skill) VALUES ('Clarion');
INSERT INTO Skills (skill) VALUES ('Clean');
INSERT INTO Skills (skill) VALUES ('Clipper');
INSERT INTO Skills (skill) VALUES ('CLIPS');
INSERT INTO Skills (skill) VALUES ('CLIST');
INSERT INTO Skills (skill) VALUES ('CLU');
INSERT INTO Skills (skill) VALUES ('CMS-2');
INSERT INTO Skills (skill) VALUES ('COBOL – ISO/IEC 1989');
INSERT INTO Skills (skill) VALUES ('CobolScript – COBOL Scripting language');
INSERT INTO Skills (skill) VALUES ('Cobra');
INSERT INTO Skills (skill) VALUES ('CoffeeScript');
INSERT INTO Skills (skill) VALUES ('ColdFusion');
INSERT INTO Skills (skill) VALUES ('COMAL');
INSERT INTO Skills (skill) VALUES ('COMIT');
INSERT INTO Skills (skill) VALUES ('Common Intermediate Language (CIL)');
INSERT INTO Skills (skill) VALUES ('Common Lisp (also known as CL)');
INSERT INTO Skills (skill) VALUES ('COMPASS');
INSERT INTO Skills (skill) VALUES ('Component Pascal');
INSERT INTO Skills (skill) VALUES ('COMTRAN');
INSERT INTO Skills (skill) VALUES ('Constraint Handling Rules (CHR)');
INSERT INTO Skills (skill) VALUES ('Control Language');
INSERT INTO Skills (skill) VALUES ('Cool');
INSERT INTO Skills (skill) VALUES ('Coq');
INSERT INTO Skills (skill) VALUES ('Coral 66');
INSERT INTO Skills (skill) VALUES ('CorVision');
INSERT INTO Skills (skill) VALUES ('COWSEL');
INSERT INTO Skills (skill) VALUES ('CPL');
INSERT INTO Skills (skill) VALUES ('Cryptol');
INSERT INTO Skills (skill) VALUES ('Csound');
INSERT INTO Skills (skill) VALUES ('Cuneiform');
INSERT INTO Skills (skill) VALUES ('Curl');
INSERT INTO Skills (skill) VALUES ('Curry');
INSERT INTO Skills (skill) VALUES ('Cybil');
INSERT INTO Skills (skill) VALUES ('Cyclone');
INSERT INTO Skills (skill) VALUES ('Cypher Query Language');
INSERT INTO Skills (skill) VALUES ('Cython');
INSERT INTO Skills (skill) VALUES ('CEEMAC');
INSERT INTO Skills (skill) VALUES ('D (also known as dlang)');
INSERT INTO Skills (skill) VALUES ('Darwin');
INSERT INTO Skills (skill) VALUES ('DataFlex');
INSERT INTO Skills (skill) VALUES ('Datalog');
INSERT INTO Skills (skill) VALUES ('DATATRIEVE');
INSERT INTO Skills (skill) VALUES ('dBase');
INSERT INTO Skills (skill) VALUES ('dc');
INSERT INTO Skills (skill) VALUES ('DCL (DIGITAL Command Language)');
INSERT INTO Skills (skill) VALUES ('Delphi');
INSERT INTO Skills (skill) VALUES ('DIBOL');
INSERT INTO Skills (skill) VALUES ('DinkC');
INSERT INTO Skills (skill) VALUES ('Dog');
INSERT INTO Skills (skill) VALUES ('Draco');
INSERT INTO Skills (skill) VALUES ('DRAKON');
INSERT INTO Skills (skill) VALUES ('Dylan');
INSERT INTO Skills (skill) VALUES ('DYNAMO');
INSERT INTO Skills (skill) VALUES ('DAX (Data Analysis Expressions)');
INSERT INTO Skills (skill) VALUES ('F');
INSERT INTO Skills (skill) VALUES ('F# (F sharp)');
INSERT INTO Skills (skill) VALUES ('F*');
INSERT INTO Skills (skill) VALUES ('Factor');
INSERT INTO Skills (skill) VALUES ('Fantom');
INSERT INTO Skills (skill) VALUES ('FAUST');
INSERT INTO Skills (skill) VALUES ('FFP');
INSERT INTO Skills (skill) VALUES ('fish');
INSERT INTO Skills (skill) VALUES ('Fjölnir');
INSERT INTO Skills (skill) VALUES ('FL');
INSERT INTO Skills (skill) VALUES ('FlagShip');
INSERT INTO Skills (skill) VALUES ('Flavors');
INSERT INTO Skills (skill) VALUES ('Flex');
INSERT INTO Skills (skill) VALUES ('Flix');
INSERT INTO Skills (skill) VALUES ('FlooP');
INSERT INTO Skills (skill) VALUES ('FLOW-MATIC (B0)');
INSERT INTO Skills (skill) VALUES ('FOCAL (Formulating On-Line Calculations in Algebraic Language/FOrmula CALculator)');
INSERT INTO Skills (skill) VALUES ('FOCUS');
INSERT INTO Skills (skill) VALUES ('FOIL');
INSERT INTO Skills (skill) VALUES ('FORMAC (FORMula MAnipulation Compiler)');
INSERT INTO Skills (skill) VALUES ('@Formula');
INSERT INTO Skills (skill) VALUES ('Forth');
INSERT INTO Skills (skill) VALUES ('Fortran – ISO/IEC 1539');
INSERT INTO Skills (skill) VALUES ('Fortress');
INSERT INTO Skills (skill) VALUES ('FP');
INSERT INTO Skills (skill) VALUES ('FoxBase/FoxPro');
INSERT INTO Skills (skill) VALUES ('Franz Lisp');
INSERT INTO Skills (skill) VALUES ('Futhark');
INSERT INTO Skills (skill) VALUES ('F-Script');
INSERT INTO Skills (skill) VALUES ('Game Maker Language');
INSERT INTO Skills (skill) VALUES ('GameMonkey Script');
INSERT INTO Skills (skill) VALUES ('GAMS (General Algebraic Modeling System)');
INSERT INTO Skills (skill) VALUES ('GAP');
INSERT INTO Skills (skill) VALUES ('G-code');
INSERT INTO Skills (skill) VALUES ('GDScript (Godot)');
INSERT INTO Skills (skill) VALUES ('Genie');
INSERT INTO Skills (skill) VALUES ('GDL (Geometric Description Language)');
INSERT INTO Skills (skill) VALUES ('GEORGE');
INSERT INTO Skills (skill) VALUES ('GLSL (OpenGL Shading Language)');
INSERT INTO Skills (skill) VALUES ('GNU E');
INSERT INTO Skills (skill) VALUES ('GNU Guile (GNU Ubiquitous Intelligent Language for Extensions)');
INSERT INTO Skills (skill) VALUES ('Go!');
INSERT INTO Skills (skill) VALUES ('GOAL (Game Oriented Assembly Lisp)');
INSERT INTO Skills (skill) VALUES ('Gödel');
INSERT INTO Skills (skill) VALUES ('Golo');
INSERT INTO Skills (skill) VALUES ('GOM (Good Old Mad)');
INSERT INTO Skills (skill) VALUES ('Google Apps Script');
INSERT INTO Skills (skill) VALUES ('Gosu');
INSERT INTO Skills (skill) VALUES ('GOTRAN (IBM 1620)');
INSERT INTO Skills (skill) VALUES ('GPSS (General Purpose Simulation System)');
INSERT INTO Skills (skill) VALUES ('GraphTalk (Computer Sciences Corporation)');
INSERT INTO Skills (skill) VALUES ('GRASS');
INSERT INTO Skills (skill) VALUES ('Grasshopper');
INSERT INTO Skills (skill) VALUES ('Groovy (Apache Groovy)');
INSERT INTO Skills (skill) VALUES ('Hack');
INSERT INTO Skills (skill) VALUES ('HAGGIS');
INSERT INTO Skills (skill) VALUES ('HAL/S');
INSERT INTO Skills (skill) VALUES ('Halide (programming language)');
INSERT INTO Skills (skill) VALUES ('Hamilton C shell');
INSERT INTO Skills (skill) VALUES ('Harbour');
INSERT INTO Skills (skill) VALUES ('Hartmann pipelines');
INSERT INTO Skills (skill) VALUES ('Haskell');
INSERT INTO Skills (skill) VALUES ('Haxe');
INSERT INTO Skills (skill) VALUES ('Hermes');
INSERT INTO Skills (skill) VALUES ('High Level Assembly (HLA)');
INSERT INTO Skills (skill) VALUES ('HLSL');
INSERT INTO Skills (skill) VALUES ('Hollywood');
INSERT INTO Skills (skill) VALUES ('HolyC (TempleOS)');
INSERT INTO Skills (skill) VALUES ('Hop');
INSERT INTO Skills (skill) VALUES ('Hopscotch');
INSERT INTO Skills (skill) VALUES ('Hope');
INSERT INTO Skills (skill) VALUES ('Hume');
INSERT INTO Skills (skill) VALUES ('HyperTalk');
INSERT INTO Skills (skill) VALUES ('Hy');
INSERT INTO Skills (skill) VALUES ('Io');
INSERT INTO Skills (skill) VALUES ('Icon');
INSERT INTO Skills (skill) VALUES ('IBM Basic assembly language');
INSERT INTO Skills (skill) VALUES ('IBM HAScript');
INSERT INTO Skills (skill) VALUES ('IBM Informix-4GL');
INSERT INTO Skills (skill) VALUES ('IBM RPG');
INSERT INTO Skills (skill) VALUES ('IDL');
INSERT INTO Skills (skill) VALUES ('Idris');
INSERT INTO Skills (skill) VALUES ('Inform');
INSERT INTO Skills (skill) VALUES ('ISLISP');
INSERT INTO Skills (skill) VALUES ('J');
INSERT INTO Skills (skill) VALUES ('J# (J sharp)');
INSERT INTO Skills (skill) VALUES ('J++ (J plus plus)');
INSERT INTO Skills (skill) VALUES ('JADE');
INSERT INTO Skills (skill) VALUES ('Jai');
INSERT INTO Skills (skill) VALUES ('JAL');
INSERT INTO Skills (skill) VALUES ('Janus (concurrent constraint programming language)');
INSERT INTO Skills (skill) VALUES ('Janus (time-reversible computing programming language)');
INSERT INTO Skills (skill) VALUES ('JASS');
INSERT INTO Skills (skill) VALUES ('JavaFX Script');
INSERT INTO Skills (skill) VALUES ('Jess');
INSERT INTO Skills (skill) VALUES ('JCL');
INSERT INTO Skills (skill) VALUES ('JEAN');
INSERT INTO Skills (skill) VALUES ('Join Java');
INSERT INTO Skills (skill) VALUES ('JOSS');
INSERT INTO Skills (skill) VALUES ('Joule');
INSERT INTO Skills (skill) VALUES ('JOVIAL');
INSERT INTO Skills (skill) VALUES ('Joy');
INSERT INTO Skills (skill) VALUES ('JScript');
INSERT INTO Skills (skill) VALUES ('JScript .NET');
INSERT INTO Skills (skill) VALUES ('Julia');
INSERT INTO Skills (skill) VALUES ('Jython');
INSERT INTO Skills (skill) VALUES ('K');
INSERT INTO Skills (skill) VALUES ('Kaleidoscope');
INSERT INTO Skills (skill) VALUES ('Karel');
INSERT INTO Skills (skill) VALUES ('KEE');
INSERT INTO Skills (skill) VALUES ('Kixtart');
INSERT INTO Skills (skill) VALUES ('Klerer-May System');
INSERT INTO Skills (skill) VALUES ('KIF (Knowledge Interchange Format)');
INSERT INTO Skills (skill) VALUES ('Kojo');
INSERT INTO Skills (skill) VALUES ('Kotlin');
INSERT INTO Skills (skill) VALUES ('KRC');
INSERT INTO Skills (skill) VALUES ('KRL');
INSERT INTO Skills (skill) VALUES ('KRL (KUKA Robot Language)');
INSERT INTO Skills (skill) VALUES ('KRYPTON');
INSERT INTO Skills (skill) VALUES ('KornShell (ksh)');
INSERT INTO Skills (skill) VALUES ('Kodu');
INSERT INTO Skills (skill) VALUES ('Kv (Kivy)');
INSERT INTO Skills (skill) VALUES ('LabVIEW');
INSERT INTO Skills (skill) VALUES ('Ladder');
INSERT INTO Skills (skill) VALUES ('LANSA');
INSERT INTO Skills (skill) VALUES ('Lasso');
INSERT INTO Skills (skill) VALUES ('Lava');
INSERT INTO Skills (skill) VALUES ('LC-3');
INSERT INTO Skills (skill) VALUES ('Lean');
INSERT INTO Skills (skill) VALUES ('Legoscript');
INSERT INTO Skills (skill) VALUES ('LIL');
INSERT INTO Skills (skill) VALUES ('LilyPond');
INSERT INTO Skills (skill) VALUES ('Limbo');
INSERT INTO Skills (skill) VALUES ('Limnor');
INSERT INTO Skills (skill) VALUES ('LINC');
INSERT INTO Skills (skill) VALUES ('Lingo');
INSERT INTO Skills (skill) VALUES ('LIS');
INSERT INTO Skills (skill) VALUES ('LISA');
INSERT INTO Skills (skill) VALUES ('Language H');
INSERT INTO Skills (skill) VALUES ('Lisp – ISO/IEC 13816');
INSERT INTO Skills (skill) VALUES ('Lite-C');
INSERT INTO Skills (skill) VALUES ('Lithe');
INSERT INTO Skills (skill) VALUES ('Little b');
INSERT INTO Skills (skill) VALUES ('LLL');
INSERT INTO Skills (skill) VALUES ('Logo');
INSERT INTO Skills (skill) VALUES ('Logtalk');
INSERT INTO Skills (skill) VALUES ('LotusScript');
INSERT INTO Skills (skill) VALUES ('LPC');
INSERT INTO Skills (skill) VALUES ('LSE');
INSERT INTO Skills (skill) VALUES ('LSL');
INSERT INTO Skills (skill) VALUES ('LiveCode');
INSERT INTO Skills (skill) VALUES ('LiveScript');
INSERT INTO Skills (skill) VALUES ('Lua');
INSERT INTO Skills (skill) VALUES ('Lucid');
INSERT INTO Skills (skill) VALUES ('Lustre');
INSERT INTO Skills (skill) VALUES ('LYaPAS');
INSERT INTO Skills (skill) VALUES ('Lynx');
INSERT INTO Skills (skill) VALUES ('M Formula language');
INSERT INTO Skills (skill) VALUES ('M2001');
INSERT INTO Skills (skill) VALUES ('M4');
INSERT INTO Skills (skill) VALUES ('M#');
INSERT INTO Skills (skill) VALUES ('Machine code');
INSERT INTO Skills (skill) VALUES ('MAD (Michigan Algorithm Decoder)');
INSERT INTO Skills (skill) VALUES ('MAD/I');
INSERT INTO Skills (skill) VALUES ('Magik');
INSERT INTO Skills (skill) VALUES ('Magma');
INSERT INTO Skills (skill) VALUES ('Máni');
INSERT INTO Skills (skill) VALUES ('Maple');
INSERT INTO Skills (skill) VALUES ('MAPPER (now part of BIS)');
INSERT INTO Skills (skill) VALUES ('MARK-IV (now VISION:BUILDER)');
INSERT INTO Skills (skill) VALUES ('Mary');
INSERT INTO Skills (skill) VALUES ('MATLAB');
INSERT INTO Skills (skill) VALUES ('MASM Microsoft Assembly x86');
INSERT INTO Skills (skill) VALUES ('MATH-MATIC');
INSERT INTO Skills (skill) VALUES ('Maude system');
INSERT INTO Skills (skill) VALUES ('Maxima (see also Macsyma)');
INSERT INTO Skills (skill) VALUES ('Max (Max Msp – Graphical Programming Environment)');
INSERT INTO Skills (skill) VALUES ('MaxScript internal language 3D Studio Max');
INSERT INTO Skills (skill) VALUES ('Maya (MEL)');
INSERT INTO Skills (skill) VALUES ('MDL');
INSERT INTO Skills (skill) VALUES ('Mercury');
INSERT INTO Skills (skill) VALUES ('Mesa');
INSERT INTO Skills (skill) VALUES ('MHEG-5 (Interactive TV programming language)');
INSERT INTO Skills (skill) VALUES ('Microcode');
INSERT INTO Skills (skill) VALUES ('Microsoft Power Fx');
INSERT INTO Skills (skill) VALUES ('MIIS');
INSERT INTO Skills (skill) VALUES ('Milk (programming language)');
INSERT INTO Skills (skill) VALUES ('MIMIC');
INSERT INTO Skills (skill) VALUES ('Mirah');
INSERT INTO Skills (skill) VALUES ('Miranda');
INSERT INTO Skills (skill) VALUES ('MIVA Script');
INSERT INTO Skills (skill) VALUES ('ML');
INSERT INTO Skills (skill) VALUES ('Model 204');
INSERT INTO Skills (skill) VALUES ('Modelica');
INSERT INTO Skills (skill) VALUES ('Malbolge');
INSERT INTO Skills (skill) VALUES ('Modula');
INSERT INTO Skills (skill) VALUES ('Modula-2');
INSERT INTO Skills (skill) VALUES ('Modula-3');
INSERT INTO Skills (skill) VALUES ('Mohol');
INSERT INTO Skills (skill) VALUES ('MOO');
INSERT INTO Skills (skill) VALUES ('Mortran');
INSERT INTO Skills (skill) VALUES ('Mouse');
INSERT INTO Skills (skill) VALUES ('MPD');
INSERT INTO Skills (skill) VALUES ('MSL');
INSERT INTO Skills (skill) VALUES ('MUMPS');
INSERT INTO Skills (skill) VALUES ('MuPAD');
INSERT INTO Skills (skill) VALUES ('Mutan');
INSERT INTO Skills (skill) VALUES ('Mystic Programming Language (MPL)');
INSERT INTO Skills (skill) VALUES ('NASM');
INSERT INTO Skills (skill) VALUES ('Napier88');
INSERT INTO Skills (skill) VALUES ('Neko');
INSERT INTO Skills (skill) VALUES ('Nemerle');
INSERT INTO Skills (skill) VALUES ('NESL');
INSERT INTO Skills (skill) VALUES ('Net.Data');
INSERT INTO Skills (skill) VALUES ('NetLogo');
INSERT INTO Skills (skill) VALUES ('NetRexx');
INSERT INTO Skills (skill) VALUES ('NewLISP');
INSERT INTO Skills (skill) VALUES ('NEWP');
INSERT INTO Skills (skill) VALUES ('Newspeak');
INSERT INTO Skills (skill) VALUES ('NewtonScript');
INSERT INTO Skills (skill) VALUES ('Nial');
INSERT INTO Skills (skill) VALUES ('Nickle (NITIN)');
INSERT INTO Skills (skill) VALUES ('Nim');
INSERT INTO Skills (skill) VALUES ('Nix (Systems configuration language)');
INSERT INTO Skills (skill) VALUES ('NPL');
INSERT INTO Skills (skill) VALUES ('Not eXactly C (NXC)');
INSERT INTO Skills (skill) VALUES ('Not Quite C (NQC)');
INSERT INTO Skills (skill) VALUES ('NSIS');
INSERT INTO Skills (skill) VALUES ('Nu');
INSERT INTO Skills (skill) VALUES ('NWScript');
INSERT INTO Skills (skill) VALUES ('NXT-G');
INSERT INTO Skills (skill) VALUES ('o:XML');
INSERT INTO Skills (skill) VALUES ('Oak');
INSERT INTO Skills (skill) VALUES ('Oberon');
INSERT INTO Skills (skill) VALUES ('OBJ2');
INSERT INTO Skills (skill) VALUES ('Object Lisp');
INSERT INTO Skills (skill) VALUES ('ObjectLOGO');
INSERT INTO Skills (skill) VALUES ('Object REXX');
INSERT INTO Skills (skill) VALUES ('Object Pascal');
INSERT INTO Skills (skill) VALUES ('Objective-C');
INSERT INTO Skills (skill) VALUES ('Obliq');
INSERT INTO Skills (skill) VALUES ('OCaml');
INSERT INTO Skills (skill) VALUES ('occam');
INSERT INTO Skills (skill) VALUES ('occam-π');
INSERT INTO Skills (skill) VALUES ('Octave');
INSERT INTO Skills (skill) VALUES ('OmniMark');
INSERT INTO Skills (skill) VALUES ('Opa');
INSERT INTO Skills (skill) VALUES ('Opal');
INSERT INTO Skills (skill) VALUES ('Open Programming Language (OPL)');
INSERT INTO Skills (skill) VALUES ('OpenCL');
INSERT INTO Skills (skill) VALUES ('OpenEdge Advanced Business Language (ABL)');
INSERT INTO Skills (skill) VALUES ('OpenVera');
INSERT INTO Skills (skill) VALUES ('OpenQASM');
INSERT INTO Skills (skill) VALUES ('OPS5');
INSERT INTO Skills (skill) VALUES ('OptimJ');
INSERT INTO Skills (skill) VALUES ('Orc');
INSERT INTO Skills (skill) VALUES ('ORCA/Modula-2');
INSERT INTO Skills (skill) VALUES ('Oriel');
INSERT INTO Skills (skill) VALUES ('Orwell');
INSERT INTO Skills (skill) VALUES ('Oxygene');
INSERT INTO Skills (skill) VALUES ('Oz');
INSERT INTO Skills (skill) VALUES ('P');
INSERT INTO Skills (skill) VALUES ('P4');
INSERT INTO Skills (skill) VALUES ('P′′');
INSERT INTO Skills (skill) VALUES ('ParaSail');
INSERT INTO Skills (skill) VALUES ('PARI/GP');
INSERT INTO Skills (skill) VALUES ('Pascal – ISO 7185');
INSERT INTO Skills (skill) VALUES ('Pascal Script');
INSERT INTO Skills (skill) VALUES ('PCASTL');
INSERT INTO Skills (skill) VALUES ('PCF');
INSERT INTO Skills (skill) VALUES ('PEARL');
INSERT INTO Skills (skill) VALUES ('PeopleCode');
INSERT INTO Skills (skill) VALUES ('Perl');
INSERT INTO Skills (skill) VALUES ('PDL');
INSERT INTO Skills (skill) VALUES ('Pharo');
INSERT INTO Skills (skill) VALUES ('PHP');
INSERT INTO Skills (skill) VALUES ('Pico');
INSERT INTO Skills (skill) VALUES ('Picolisp');
INSERT INTO Skills (skill) VALUES ('Pict');
INSERT INTO Skills (skill) VALUES ('Pike');
INSERT INTO Skills (skill) VALUES ('PILOT');
INSERT INTO Skills (skill) VALUES ('Pipelines');
INSERT INTO Skills (skill) VALUES ('Pizza');
INSERT INTO Skills (skill) VALUES ('PL-11');
INSERT INTO Skills (skill) VALUES ('PL/0');
INSERT INTO Skills (skill) VALUES ('PL/B');
INSERT INTO Skills (skill) VALUES ('PL/C');
INSERT INTO Skills (skill) VALUES ('PL/I – ISO 6160');
INSERT INTO Skills (skill) VALUES ('PL/M');
INSERT INTO Skills (skill) VALUES ('PL/P');
INSERT INTO Skills (skill) VALUES ('PL/S');
INSERT INTO Skills (skill) VALUES ('PL/SQL');
INSERT INTO Skills (skill) VALUES ('PL360');
INSERT INTO Skills (skill) VALUES ('PLANC');
INSERT INTO Skills (skill) VALUES ('Plankalkül');
INSERT INTO Skills (skill) VALUES ('Planner');
INSERT INTO Skills (skill) VALUES ('PLEX');
INSERT INTO Skills (skill) VALUES ('PLEXIL');
INSERT INTO Skills (skill) VALUES ('Plus');
INSERT INTO Skills (skill) VALUES ('POP-11');
INSERT INTO Skills (skill) VALUES ('POP-2');
INSERT INTO Skills (skill) VALUES ('PostScript');
INSERT INTO Skills (skill) VALUES ('PortablE');
INSERT INTO Skills (skill) VALUES ('POV-Ray SDL');
INSERT INTO Skills (skill) VALUES ('Powerhouse');
INSERT INTO Skills (skill) VALUES ('PowerBuilder – 4GL GUI application generator from Sybase');
INSERT INTO Skills (skill) VALUES ('PPL');
INSERT INTO Skills (skill) VALUES ('Processing');
INSERT INTO Skills (skill) VALUES ('Processing.js');
INSERT INTO Skills (skill) VALUES ('Prograph');
INSERT INTO Skills (skill) VALUES ('Project Verona');
INSERT INTO Skills (skill) VALUES ('Prolog');
INSERT INTO Skills (skill) VALUES ('PROMAL');
INSERT INTO Skills (skill) VALUES ('Promela');
INSERT INTO Skills (skill) VALUES ('PROSE modeling language');
INSERT INTO Skills (skill) VALUES ('PROTEL');
INSERT INTO Skills (skill) VALUES ('ProvideX');
INSERT INTO Skills (skill) VALUES ('Pro*C');
INSERT INTO Skills (skill) VALUES ('Pure');
INSERT INTO Skills (skill) VALUES ('Pure Data');
INSERT INTO Skills (skill) VALUES ('PWCT');
INSERT INTO Skills (skill) VALUES ('Q (programming language from Kx Systems)');
INSERT INTO Skills (skill) VALUES ('Q# (Microsoft programming language)');
INSERT INTO Skills (skill) VALUES ('Qalb');
INSERT INTO Skills (skill) VALUES ('Quantum Computation Language');
INSERT INTO Skills (skill) VALUES ('QtScript');
INSERT INTO Skills (skill) VALUES ('QuakeC');
INSERT INTO Skills (skill) VALUES ('QPL');
INSERT INTO Skills (skill) VALUES ('.QL');
INSERT INTO Skills (skill) VALUES ('R');
INSERT INTO Skills (skill) VALUES ('R++');
INSERT INTO Skills (skill) VALUES ('Racket');
INSERT INTO Skills (skill) VALUES ('Raku');
INSERT INTO Skills (skill) VALUES ('RAPID');
INSERT INTO Skills (skill) VALUES ('Rapira');
INSERT INTO Skills (skill) VALUES ('Ratfiv');
INSERT INTO Skills (skill) VALUES ('Ratfor');
INSERT INTO Skills (skill) VALUES ('rc');
INSERT INTO Skills (skill) VALUES ('Reason');
INSERT INTO Skills (skill) VALUES ('REBOL');
INSERT INTO Skills (skill) VALUES ('Red');
INSERT INTO Skills (skill) VALUES ('Redcode');
INSERT INTO Skills (skill) VALUES ('REFAL');
INSERT INTO Skills (skill) VALUES ('REXX');
INSERT INTO Skills (skill) VALUES ('Ring');
INSERT INTO Skills (skill) VALUES ('ROOP');
INSERT INTO Skills (skill) VALUES ('RPG');
INSERT INTO Skills (skill) VALUES ('RPL');
INSERT INTO Skills (skill) VALUES ('RSL');
INSERT INTO Skills (skill) VALUES ('RTL/2');
INSERT INTO Skills (skill) VALUES ('Rust');
INSERT INTO Skills (skill) VALUES ('S');
INSERT INTO Skills (skill) VALUES ('S2');
INSERT INTO Skills (skill) VALUES ('S3');
INSERT INTO Skills (skill) VALUES ('S-Lang');
INSERT INTO Skills (skill) VALUES ('S-PLUS');
INSERT INTO Skills (skill) VALUES ('SA-C');
INSERT INTO Skills (skill) VALUES ('SabreTalk');
INSERT INTO Skills (skill) VALUES ('SAIL');
INSERT INTO Skills (skill) VALUES ('SAKO');
INSERT INTO Skills (skill) VALUES ('SAS');
INSERT INTO Skills (skill) VALUES ('SASL');
INSERT INTO Skills (skill) VALUES ('Sather');
INSERT INTO Skills (skill) VALUES ('Sawzall');
INSERT INTO Skills (skill) VALUES ('Scala');
INSERT INTO Skills (skill) VALUES ('Scheme');
INSERT INTO Skills (skill) VALUES ('Scilab');
INSERT INTO Skills (skill) VALUES ('Scratch');
INSERT INTO Skills (skill) VALUES ('Script.NET');
INSERT INTO Skills (skill) VALUES ('Sed');
INSERT INTO Skills (skill) VALUES ('Seed7');
INSERT INTO Skills (skill) VALUES ('Self');
INSERT INTO Skills (skill) VALUES ('SenseTalk');
INSERT INTO Skills (skill) VALUES ('SequenceL');
INSERT INTO Skills (skill) VALUES ('Serpent');
INSERT INTO Skills (skill) VALUES ('SETL');
INSERT INTO Skills (skill) VALUES ('Short Code');
INSERT INTO Skills (skill) VALUES ('SIMPOL');
INSERT INTO Skills (skill) VALUES ('SIGNAL');
INSERT INTO Skills (skill) VALUES ('SiMPLE');
INSERT INTO Skills (skill) VALUES ('SIMSCRIPT');
INSERT INTO Skills (skill) VALUES ('Simula');
INSERT INTO Skills (skill) VALUES ('Simulink');
INSERT INTO Skills (skill) VALUES ('SISAL');
INSERT INTO Skills (skill) VALUES ('SKILL');
INSERT INTO Skills (skill) VALUES ('SLIP');
INSERT INTO Skills (skill) VALUES ('SMALL');
INSERT INTO Skills (skill) VALUES ('Smalltalk');
INSERT INTO Skills (skill) VALUES ('SML');
INSERT INTO Skills (skill) VALUES ('Strongtalk');
INSERT INTO Skills (skill) VALUES ('Snap!');
INSERT INTO Skills (skill) VALUES ('SNOBOL (SPITBOL)');
INSERT INTO Skills (skill) VALUES ('Snowball');
INSERT INTO Skills (skill) VALUES ('SOL');
INSERT INTO Skills (skill) VALUES ('Solidity');
INSERT INTO Skills (skill) VALUES ('SOPHAEROS');
INSERT INTO Skills (skill) VALUES ('Source');
INSERT INTO Skills (skill) VALUES ('SPARK');
INSERT INTO Skills (skill) VALUES ('Speakeasy');
INSERT INTO Skills (skill) VALUES ('Speedcode');
INSERT INTO Skills (skill) VALUES ('SPIN');
INSERT INTO Skills (skill) VALUES ('SP/k');
INSERT INTO Skills (skill) VALUES ('SPS');
INSERT INTO Skills (skill) VALUES ('SQR');
INSERT INTO Skills (skill) VALUES ('Squeak');
INSERT INTO Skills (skill) VALUES ('Squirrel');
INSERT INTO Skills (skill) VALUES ('SR');
INSERT INTO Skills (skill) VALUES ('S/SL');
INSERT INTO Skills (skill) VALUES ('Starlogo');
INSERT INTO Skills (skill) VALUES ('Strand');
INSERT INTO Skills (skill) VALUES ('Stata');
INSERT INTO Skills (skill) VALUES ('Stateflow');
INSERT INTO Skills (skill) VALUES ('Subtext');
INSERT INTO Skills (skill) VALUES ('SBL');
INSERT INTO Skills (skill) VALUES ('SuperCollider');
INSERT INTO Skills (skill) VALUES ('Superplan');
INSERT INTO Skills (skill) VALUES ('SuperTalk');
INSERT INTO Skills (skill) VALUES ('Swift (Apple programming language)');
INSERT INTO Skills (skill) VALUES ('Swift (parallel scripting language)');
INSERT INTO Skills (skill) VALUES ('SYMPL');
INSERT INTO Skills (skill) VALUES ('T');
INSERT INTO Skills (skill) VALUES ('TACL');
INSERT INTO Skills (skill) VALUES ('TACPOL');
INSERT INTO Skills (skill) VALUES ('TADS (Text Adventure Development System)');
INSERT INTO Skills (skill) VALUES ('TAL');
INSERT INTO Skills (skill) VALUES ('Tcl');
INSERT INTO Skills (skill) VALUES ('Tea');
INSERT INTO Skills (skill) VALUES ('TECO (Text Editor and Corrector)');
INSERT INTO Skills (skill) VALUES ('TELCOMP');
INSERT INTO Skills (skill) VALUES ('TeX');
INSERT INTO Skills (skill) VALUES ('TEX (Text Executive Programming Language)');
INSERT INTO Skills (skill) VALUES ('TIE');
INSERT INTO Skills (skill) VALUES ('TMG (TransMo Griffer), compiler-compiler');
INSERT INTO Skills (skill) VALUES ('Tom');
INSERT INTO Skills (skill) VALUES ('Toi');
INSERT INTO Skills (skill) VALUES ('Topspeed (Clarion)');
INSERT INTO Skills (skill) VALUES ('TPU (Text Processing Utility)');
INSERT INTO Skills (skill) VALUES ('Trac');
INSERT INTO Skills (skill) VALUES ('TTM');
INSERT INTO Skills (skill) VALUES ('T-SQL (Transact-SQL)');
INSERT INTO Skills (skill) VALUES ('Transcript (LiveCode)');
INSERT INTO Skills (skill) VALUES ('TTCN (Tree and Tabular Combined Notation)');
INSERT INTO Skills (skill) VALUES ('Turing');
INSERT INTO Skills (skill) VALUES ('TUTOR (PLATO Author Language)');
INSERT INTO Skills (skill) VALUES ('TXL');
INSERT INTO Skills (skill) VALUES ('TypeScript');
INSERT INTO Skills (skill) VALUES ('Tynker');
INSERT INTO Skills (skill) VALUES ('Ubercode');
INSERT INTO Skills (skill) VALUES ('UCSD Pascal');
INSERT INTO Skills (skill) VALUES ('Umple');
INSERT INTO Skills (skill) VALUES ('Unicon');
INSERT INTO Skills (skill) VALUES ('Uniface');
INSERT INTO Skills (skill) VALUES ('UNITY');
INSERT INTO Skills (skill) VALUES ('UnrealScript');
INSERT INTO Skills (skill) VALUES ('Vala');
INSERT INTO Skills (skill) VALUES ('Vim script');
INSERT INTO Skills (skill) VALUES ('Viper (Ethereum/Ether (ETH))');
INSERT INTO Skills (skill) VALUES ('Visual DataFlex');
INSERT INTO Skills (skill) VALUES ('Visual DialogScript');
INSERT INTO Skills (skill) VALUES ('Visual FoxPro');
INSERT INTO Skills (skill) VALUES ('Visual J++ (Visual J plus plus)');
INSERT INTO Skills (skill) VALUES ('Visual LISP');
INSERT INTO Skills (skill) VALUES ('Visual Objects');
INSERT INTO Skills (skill) VALUES ('Visual Prolog');
INSERT INTO Skills (skill) VALUES ('X++ (X plus plus/Microsoft Dynamics AX)');
INSERT INTO Skills (skill) VALUES ('X10');
INSERT INTO Skills (skill) VALUES ('xBase++ (xBase plus plus)');
INSERT INTO Skills (skill) VALUES ('XBL');
INSERT INTO Skills (skill) VALUES ('XC (targets XMOS architecture)');
INSERT INTO Skills (skill) VALUES ('xHarbour');
INSERT INTO Skills (skill) VALUES ('XL');
INSERT INTO Skills (skill) VALUES ('Xojo');
INSERT INTO Skills (skill) VALUES ('XOTcl');
INSERT INTO Skills (skill) VALUES ('Xod');
INSERT INTO Skills (skill) VALUES ('XPL');
INSERT INTO Skills (skill) VALUES ('XPL0');
INSERT INTO Skills (skill) VALUES ('XSB');
INSERT INTO Skills (skill) VALUES ('XSharp (X#)');
INSERT INTO Skills (skill) VALUES ('XSLT');
INSERT INTO Skills (skill) VALUES ('Xtend');